

#CaR Board Digital Inputs (CMOS_IN) (ASIC Digital Outputs)
set_property PACKAGE_PIN AB11 [get_ports {CMOS_IN_1_clk_p[0]}]
set_property PACKAGE_PIN AB10 [get_ports {CMOS_IN_1_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_1_*]
set_property PACKAGE_PIN AA11 [get_ports {CMOS_IN_2_clk_p[0]}]
set_property PACKAGE_PIN AA10 [get_ports {CMOS_IN_2_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_2_*]
set_property PACKAGE_PIN AF11 [get_ports {CMOS_IN_3_clk_p[0]}]
set_property PACKAGE_PIN AG11 [get_ports {CMOS_IN_3_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_3_*]
set_property PACKAGE_PIN AC12 [get_ports {CMOS_IN_4_clk_p[0]}]
set_property PACKAGE_PIN AC11 [get_ports {CMOS_IN_4_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_4_*]
set_property PACKAGE_PIN AE10 [get_ports {CMOS_IN_5_clk_p[0]}]
set_property PACKAGE_PIN AF10 [get_ports {CMOS_IN_5_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_5_*]
set_property PACKAGE_PIN AH12 [get_ports {CMOS_IN_6_clk_p[0]}]
set_property PACKAGE_PIN AH11 [get_ports {CMOS_IN_6_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_6_*]
set_property PACKAGE_PIN W12 [get_ports {CMOS_IN_7_clk_p[0]}]
set_property PACKAGE_PIN W11 [get_ports {CMOS_IN_7_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_7_*]
set_property PACKAGE_PIN T13 [get_ports {CMOS_IN_8_clk_p[0]}]
set_property PACKAGE_PIN R13 [get_ports {CMOS_IN_8_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_8_*]
set_property PACKAGE_PIN T12 [get_ports {CMOS_IN_9_clk_p[0]}]
set_property PACKAGE_PIN R12 [get_ports {CMOS_IN_9_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_9_*]
set_property PACKAGE_PIN V8 [get_ports {CMOS_IN_10_clk_p[0]}]
set_property PACKAGE_PIN V7 [get_ports {CMOS_IN_10_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_10_*]
set_property PACKAGE_PIN AD7 [get_ports {CMOS_IN_11_clk_p[0]}]
set_property PACKAGE_PIN AD6 [get_ports {CMOS_IN_11_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_11_*]
set_property PACKAGE_PIN V6 [get_ports {CMOS_IN_12_clk_p[0]}]
set_property PACKAGE_PIN U6 [get_ports {CMOS_IN_12_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_12_*]
set_property PACKAGE_PIN V12 [get_ports {CMOS_IN_13_clk_p[0]}]
set_property PACKAGE_PIN V11 [get_ports {CMOS_IN_13_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_13_*]
set_property PACKAGE_PIN U11 [get_ports {CMOS_IN_14_clk_p[0]}]
set_property PACKAGE_PIN T11 [get_ports {CMOS_IN_14_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_IN_14_*]


#CaR Board Digital Outputs (CMOS_OUT) (ASIC Digital Inputs)

set_property PACKAGE_PIN T7 [get_ports {CMOS_OUT_1_clk_p[0]}]
set_property PACKAGE_PIN T6 [get_ports {CMOS_OUT_1_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_1_*]
set_property PACKAGE_PIN U9 [get_ports {CMOS_OUT_2_clk_p[0]}]
set_property PACKAGE_PIN U8 [get_ports {CMOS_OUT_2_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_2_*]
set_property PACKAGE_PIN L12 [get_ports {CMOS_OUT_3_clk_p[0]}]
set_property PACKAGE_PIN K12 [get_ports {CMOS_OUT_3_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_3_*]
set_property PACKAGE_PIN M11 [get_ports {CMOS_OUT_4_clk_p[0]}]
set_property PACKAGE_PIN L11 [get_ports {CMOS_OUT_4_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_4_*]
set_property PACKAGE_PIN L15 [get_ports {CMOS_OUT_5_clk_p[0]}]
set_property PACKAGE_PIN K15 [get_ports {CMOS_OUT_5_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_5_*]
set_property PACKAGE_PIN M10 [get_ports {CMOS_OUT_6_clk_p[0]}]
set_property PACKAGE_PIN L10 [get_ports {CMOS_OUT_6_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_6_*]
set_property PACKAGE_PIN L16 [get_ports {CMOS_OUT_7_clk_p[0]}]
set_property PACKAGE_PIN K16 [get_ports {CMOS_OUT_7_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_7_*]
set_property PACKAGE_PIN N9 [get_ports {CMOS_OUT_8_clk_p[0]}]
set_property PACKAGE_PIN N8 [get_ports {CMOS_OUT_8_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_8_*]
set_property PACKAGE_PIN AH1 [get_ports {CMOS_OUT_9_clk_p[0]}]
set_property PACKAGE_PIN AJ1 [get_ports {CMOS_OUT_9_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_9_*]
set_property PACKAGE_PIN AE3 [get_ports {CMOS_OUT_10_clk_p[0]}]
set_property PACKAGE_PIN AF3 [get_ports {CMOS_OUT_10_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports CMOS_OUT_10_*]

#CaR Board Injection Pulser Controls

set_property PACKAGE_PIN AE3 [get_ports {INJ_CTRL_1_clk_p[0]}]
set_property PACKAGE_PIN AF3 [get_ports {INJ_CTRL_1_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports INJ_CTRL_1_*]
set_property PACKAGE_PIN AE3 [get_ports {INJ_CTRL_2_clk_p[0]}]
set_property PACKAGE_PIN AF3 [get_ports {INJ_CTRL_2_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports INJ_CTRL_2_*]
set_property PACKAGE_PIN AE3 [get_ports {INJ_CTRL_3_clk_p[0]}]
set_property PACKAGE_PIN AF3 [get_ports {INJ_CTRL_3_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports INJ_CTRL_3_*]
set_property PACKAGE_PIN AE3 [get_ports {INJ_CTRL_4_clk_p[0]}]
set_property PACKAGE_PIN AF3 [get_ports {INJ_CTRL_4_clk_n[0]}]
set_property IOSTANDARD LVDS [get_ports INJ_CTRL_4_*]